apiVersion: v1
kind: Service
metadata:
  name: "{{.Release.Name}}-{{.Values.component}}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.component}}" 
spec: 
  selector:
    component: "{{.Release.Name}}-{{.Values.component}}"  
  ports:
  - name: beats
    port: {{.Values.beats.port}}
    protocol: TCP
  - name: tcp
    port: {{.Values.tcp.port}}
    protocol: TCP