apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Release.Name}}-{{.Values.component}}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.component}}" 
data:
{{ toYaml .Values.config | indent 2 }}