# Default values for piapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.unimatrix0.je-labs/demo/piui
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: piapp
  type: ClusterIP
  externalPort: 5002
  internalPort: 5002
resources: 
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 300m
    memory: 256Mi

pi_app_service: "piapp-piapp"
pi_app_port: 5001
pi_app_protocol: "http://"

ingress:
  postfix: "mars.unimatrix0.je-labs.com"
  name: "piui"