apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{template "fullname" .}}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}    
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Chart.Name }}
spec:
  rules:
{{ toYaml .Values.rules | indent 2 }}
