apiVersion: v1
kind: Pod
metadata:
  name: {{ template "pischema.fullname" . }}
  labels:
    app: pod-schema
spec:
  containers:
  - name: {{ .Chart.Name }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ template "mysqldb.fullname" . }}
          key: mysql-root-password
    - name: MYSQL_PASSWORD
      value: {{ .Values.mysql.mysqlPassword }}
    - name: MYSQL_HOSTNAME
      value: {{ template "mysqldb.fullname" . }}
    - name: MYSQL_USERNAME
      value: {{ default "" .Values.mysql.mysqlUser | quote }}
    - name: MYSQL_DATABASE
      value: {{ default "" .Values.mysql.mysqlDatabase | quote }}
    - name: DEBUG
      value: {{ default "false" .Values.debug | quote }}
    - name: POD_NAMESPACE
      value: {{ default "" .Release.Namespace | quote }}


    #resources:
    #  limits:
    #    memory: 512Mi
    #    cpu: 1
    #  requests:
    #    memory: 128Mi
    #    cpu: 500mi
 
