# Default values for piapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 044366197691.dkr.ecr.eu-west-1.amazonaws.com/demo/piapp
  tag: 1.0.16
  pullPolicy: IfNotPresent
service:
  name: piapp
  type: ClusterIP
  externalPort: 5001
  internalPort: 5001
resources: 
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

schema:
  repository: 044366197691.dkr.ecr.eu-west-1.amazonaws.com/demo/piapp-schema
  tag: 11
  pullPolicy: IfNotPresent


mysql:
  server: localhost 
  user: piapp
  password: abc123345
  database: piapp
  port: 3306
