# Default values for piapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.unimatrix0.je-labs/demo/piapp
  tag: 1.0.16
  pullPolicy: IfNotPresent
service:
  name: piapp
  type: ClusterIP
  externalPort: 5001
  internalPort: 5001
resources: 
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 300m
    memory: 256Mi

schema:
  repository: registry.unimatrix0.je-labs/demo/piapp-schema
  tag: 11
  pullPolicy: IfNotPresent


mysql:
  server: localhost 
  user: piapp
  password: abc123345
  database: piapp
  port: 3306
