apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "%s-%s-discovery" .Release.Name .Values.Name | trunc 24 }}" 
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
    role: master
spec:
  selector:
    component: "{{.Release.Name}}-{{.Values.Component}}"
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
