apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "piapp.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ template "piapp.fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: configmap-{{ template "piapp.name" . }}
data:
  appsettings.json: |+ 
    ﻿{
      "connection": "server={{ .Values.mysql.server }}.{{ .Release.Namespace }};user id={{ .Values.mysql.user }};password={{ .Values.mysql.password }};persistsecurityinfo=True;port=3306;database={{ .Values.mysql.database }}"
    }