apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "piapp.fullname" . }}
  labels:
    app: {{ template "piapp.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "piapp.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.internalPort }}
          volumeMounts:
          - mountPath: /dotnetapp/config
            name: config-volume
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: configmap-{{ template "piapp.fullname" . }}